stages:
- lint

lint:
  stage: lint
  image: gradle:jdk11
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle check
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
