version: '3'
services:
  help-db:
    restart: always
    container_name: help-db
    image: postgres:10.15-alpine
    environment:
      POSTGRES_ROOT_PASSWORD: rootPassword
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: UwMnRZ8ds8aioT
      POSTGRES_DATABASE: help 
    ports:
      -  5433:5432

  help-web:
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - help-db
